/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/buses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Buses */
        get: operations["get_buses_api_buses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stops/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Stops */
        get: operations["search_stops_api_stops_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate Route */
        get: operations["calculate_route_api_route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Retourne le top 10 des signaleurs + stats globales communauté.
         *     FIX BUG-C4 : retourne tous les champs attendus par le frontend.
         */
        get: operations["get_leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Report */
        post: operations["post_report_api_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscriptions
         * @description Retourne les lignes actives pour ce session_id.
         */
        get: operations["get_subscriptions_api_subscriptions_get"];
        put?: never;
        /**
         * Create Subscription
         * @description Crée ou réactive un abonnement.
         */
        post: operations["create_subscription_api_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/{ligne}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Subscription
         * @description Désactive un abonnement.
         */
        delete: operations["delete_subscription_api_subscriptions__ligne__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracking/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tracking Update
         * @description Reçoit une position GPS et enregistre le bus Dem Dikk le plus proche.
         *
         *     Priorité pour la ligne :
         *       1. body.ligne (fourni explicitement par le client)
         *       2. session LangGraph de l'usager (ex: il venait de demander "Bus 15 est où ?")
         *       3. Aucune → on prend la 1ère ligne de l'arrêt le plus proche
         *
         *     Retourne :
         *       {"status": "ok",           "ligne": "...", "arret": "..."}  ← succès
         *       {"status": "no_stop_found"}                                  ← aucun arrêt proche
         *       {"status": "spam"}                                           ← anti-spam déclenché
         *       {"status": "db_error"}                                       ← erreur Supabase
         */
        post: operations["tracking_update_tracking_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BusPosition */
        BusPosition: {
            /** Ligne */
            ligne: string;
            /** Arret Signale */
            arret_signale: string;
            /** Arret Estime */
            arret_estime: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Au Terminus */
            au_terminus: boolean;
            /** Arret Index Depart */
            arret_index_depart: number | null;
            /** Arret Index Estime */
            arret_index_estime: number;
            /** Arrets Total */
            arrets_total: number;
            /** Next Arret */
            next_arret: string | null;
            /** Progress To Next */
            progress_to_next: number;
            /** Route Window */
            route_window: components["schemas"]["RouteWindowStop"][];
            /** Repart Dans Min */
            repart_dans_min: number | null;
            /** Minutes Depuis Signalement */
            minutes_depuis_signalement: number;
            confiance: components["schemas"]["ConfidenceBadge"];
            /** Go Sessions Count */
            go_sessions_count: number;
            /** Confirmation Count */
            confirmation_count: number;
            /**
             * Confidence Level
             * @enum {string}
             */
            confidence_level: "low" | "medium" | "high";
            /** Confidence Reason */
            confidence_reason: string;
            /**
             * Tracking Mode
             * @enum {string}
             */
            tracking_mode: "live_gps" | "community" | "estimated";
            /** Tracking Freshness Sec */
            tracking_freshness_sec: number | null;
            /** Tracking Reason */
            tracking_reason: string;
        };
        /** BusesResponse */
        BusesResponse: {
            /** Buses */
            buses: components["schemas"]["BusPosition"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Timestamp */
            timestamp?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ConfidenceBadge */
        ConfidenceBadge: {
            /**
             * Niveau
             * @enum {string}
             */
            niveau: "vert" | "jaune" | "rouge";
            /** Emoji */
            emoji: string;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardBadge */
        LeaderboardBadge: {
            /** Emoji */
            emoji: string;
            /** Label */
            label: string;
            /** Niveau */
            niveau: number;
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Rang */
            rang: number;
            /** Pseudo */
            pseudo: string;
            /** Nb Signalements */
            nb_signalements: number;
            /** Fiabilite Score */
            fiabilite_score: number;
            badge: components["schemas"]["LeaderboardBadge"];
            /** Name */
            name: string;
            /** Avatar */
            avatar: string;
            /** Zone */
            zone: string;
            /** Count */
            count: number;
            /** Badges */
            badges: string[];
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /** Leaderboard */
            leaderboard: components["schemas"]["LeaderboardEntry"][];
            stats: components["schemas"]["LeaderboardStats"];
            /** Error */
            error?: string | null;
        };
        /** LeaderboardStats */
        LeaderboardStats: {
            /**
             * Total Signalements Aujourd Hui
             * @default 0
             */
            total_signalements_aujourd_hui: number;
            /**
             * Total Signalements All Time
             * @default 0
             */
            total_signalements_all_time: number;
            /**
             * Nb Contributeurs
             * @default 0
             */
            nb_contributeurs: number;
        };
        /** ReportPayload */
        ReportPayload: {
            /** Ligne */
            ligne: string;
            /** Arret */
            arret: string;
            /** Observation */
            observation?: string | null;
            /**
             * Source
             * @default web_dashboard
             */
            source: string | null;
            /** Client Ts */
            client_ts?: string | null;
            /** Session Id */
            session_id?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Nearest Stop */
            nearest_stop?: string | null;
            /** Signalement Id */
            signalement_id?: string | null;
        };
        /** RouteResponse */
        RouteResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "stop_not_found" | "same_stop" | "direct" | "walk_direct" | "no_transfer_not_found" | "transfer" | "not_found";
            /** Origin Query */
            origin_query?: string | null;
            /** Dest Query */
            dest_query?: string | null;
            /** Origin Display */
            origin_display?: string | null;
            /** Dest Display */
            dest_display?: string | null;
            /** Which */
            which?: ("origin" | "dest") | null;
            /** Query */
            query?: string | null;
            /** Stop */
            stop?: string | null;
            /** Routes */
            routes?: {
                [key: string]: unknown;
            }[] | null;
            /** Alt Transfer */
            alt_transfer?: {
                [key: string]: unknown;
            } | null;
            /** Alt Walk */
            alt_walk?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** RouteWindowStop */
        RouteWindowStop: {
            /** Nom */
            nom: string;
            /** Index */
            index: number;
            /**
             * State
             * @enum {string}
             */
            state: "passed" | "current" | "next";
        };
        /** StopLine */
        StopLine: {
            /** Numero */
            numero: string;
            /** Has Recent */
            has_recent: boolean;
            /** Last Seen Min */
            last_seen_min: number | null;
        };
        /** StopSearchResult */
        StopSearchResult: {
            /** Nom */
            nom: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Distance M */
            distance_m: number | null;
            /** Lignes */
            lignes: components["schemas"]["StopLine"][];
        };
        /** StopsSearchResponse */
        StopsSearchResponse: {
            /** Stops */
            stops: components["schemas"]["StopSearchResult"][];
            /** Total */
            total: number;
            /** Query */
            query: string;
            /** Via Secteur */
            via_secteur?: string | null;
        };
        /** SubscriptionCreate */
        SubscriptionCreate: {
            /** Session Id */
            session_id: string;
            /** Ligne */
            ligne: string;
        };
        /** TrackingUpdate */
        TrackingUpdate: {
            /** Phone */
            phone: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Ligne */
            ligne?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_buses_api_buses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusesResponse"];
                };
            };
        };
    };
    search_stops_api_stops_search_get: {
        parameters: {
            query: {
                q: string;
                lat?: number | null;
                lon?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopsSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_route_api_route_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                no_transfer?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
        };
    };
    post_report_api_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscriptions_api_subscriptions_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subscription_api_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_api_subscriptions__ligne__delete: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path: {
                ligne: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tracking_update_tracking_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
